# Pandas核心数据结构/类

### 核心数据结构：Series和Dataframe，用来组织和存放数据

# Series数据类型

In [ ]:
'''
Series可以理解为一行或一列数据，类似于一维数组，由索引index和值value组成
在Pandas中其实是没有行的概念的，任何数据取出来都是以列的形式
'''
import pandas as pd
import numpy as np

## 创建Series对象

In [ ]:
#自定义Series对象
s1=pd.Series([1,2,3,4,5])   #没有写index，就会默认自增索引
print(s1)

In [ ]:
#自定义Series对象，采用自定义索引
s2=pd.Series([1,2,3,4,5],index=['a','b','c','d','e'])   #列表形式，常用形式
s22=pd.Series([i for i in range(5)],index=['a','b','c','d','e'])    #列表推导式
print(s22)

In [ ]:
#自定义Series对象，采用元组形式
s3=pd.Series((1,2,3,4,5),index=('a','b','c','d','e'))   #元组形式，元组是不可变对象，传给pandas之后，会被转换成index对象
print(s3)
#自定义Series对象，采用词典形式
s4=pd.Series({'a':1,'b':2,'c':3,'d':5})   #词典形式
print(s4)

In [ ]:
#采用numpy创建Series对象
s5=pd.Series(np.arange(5))
print(s5)

## Series对象的属性

In [ ]:
#构建Series对象
s6=pd.Series(data=[i for i in range(6)],index=[j for j in 'ABCDEF'])    #列表推导式
print(s6)

In [ ]:
#获取Series对象的索引列
print(s6.index)

In [ ]:
#获取Series对象的值
print(s6.values)

In [ ]:
#根据索引获取元素
print(s6['D'])

In [ ]:
#根据索引修改Series对象的元素值
s6['A']=39
print(s6)

# Dataframe数据类型

In [ ]:
#Dataframe是一个类似于二维数组或表格的对象，即有行索引（index），又有列索引（solumns）
#axis=0，代表行索引，sum(axis=0)代表，按上下的方向求和，最后得到一行，axis=1则代表按左右的方向进行操作，最后得到一列

## 创建Dataframe对象

In [ ]:
#采用字典+列表形式创建，在字典里面嵌套列表 （最推荐）
info = {
    '姓名':['zbw','xjx','myy','shy'],
    '年龄':[18,18,18,18],
    '性别':['男','女','男','女'],
}
#将上述数据封装成Dataframe对象
d1=pd.DataFrame(data=info,index=['a','b','c','d'])  #默认情况下，字典的键名就是列名，值就是列数据
print(d1)

In [ ]:
#字典套字典套列表
info={'a':{'姓名':'zbw','年龄':18,'性别':'男'},
      'b':{'姓名':'myy','年龄':18,'性别':'男'},
      'c':{'姓名':'xjx','年龄':18,'性别':'女'},        #字典套字典的情况下，外层字典的键名为列名。内层字典的键名为行名,一个内层字典就是一列数据
}
d2=pd.DataFrame(data=info)
print(d2)

In [ ]:
#列表套元组、列表套列表
info=[['zbw',18,'nan'],
      ['myy',18,'nan'],
      ['xjx',18,'nv'],
]
info=[  ('zbw',18,'nan'),
        ('myy',18,'nan'),
        ('xjx',18,'nv'),
]
d3=pd.DataFrame(data=info,index=['a','c','b'],columns=['姓名','年龄','性别'])
print(d3)

In [ ]:
#通过numpy的ndarray对象，创建Dataframe对象
#创建ndarray对象
a1=np.arange(0,12).reshape(3,4)
print(a1)
d4=pd.DataFrame(data=a1,index=[1,2,3],columns=['a','b','c','d'])
print(d4)

## Dataframe数据类型简单案例

In [ ]:
#生成10名同学5门功课的成绩，范围40-100
info=np.random.randint(40,101,(10,5))   #左闭右开
print(info)

In [ ]:
#封装为Dataframe对象
score_list=pd.DataFrame(info)
print(score_list)

In [ ]:
#修改索引和列名字
column_names=['语文','数学','英语','物理','化学']
index_names=['同学'+str(i) for i in range(1,score_list.shape[0]+1)]
#方法1
# score_list.index=index_names
# score_list.columns=column_names
#方法2,通过rename精准修改，需要传入字典
score_list.rename(columns={i: column_names[i] for i in range(len(column_names))}, index={i: index_names[i] for i in range(len(index_names))}, inplace=True)     #字典推导式 i：column_names[i] for i in 10 字典的键值对都会遍历
# print(score_list)
score_list

In [ ]:
score_list.shape[0]

## dataFrame基本属性

In [ ]:
#基本属性包括：纬度（行列数），索引列，列名，数据，行列转置等等
print('score_list的维度为：',score_list.shape)   #shape属性，返回一个元组，包含行数和列数
print('score_list的行数为：',score_list.shape[0])   #shape属性，返回一个元组，包含行数和列数
print('score_list的列数为：',score_list.shape[1])   #shape属性，返回一个元组，包含行数和列数
print('score_list的索引列为：',score_list.index)   #index属性，返回索引列
print('score_list的列名为：',score_list.columns)   #columns属性，返回列名
print('score_list的数据为：',score_list.values)       #data属性，返回数据
print('score_list的行列转置为：',score_list.T)       #T属性，返回行列转置

## dataFrame基本函数

In [ ]:
#查看前n行数据head(n)，不写n默认是五行
score_list.head(4)

In [ ]:
#查看后n行数据tail(n)，不写n默认是五行
score_list.tail(4)

In [ ]:
#info(),查看数据的详细信息，包括数据类型，非空值数量，内存占用情况等
score_list.info()

In [ ]:
#describe(),查看数据的基本统计信息，包括计数、均值、标准差、最小值、最大值、四分位数等
score_list.describe()

In [ ]:
#reset_index(),重置索引
score_list.reset_index(drop=False,inplace=True)   #drop=False表示保留原来的索引列，inplace=True表示在原来的数据上进行修改
score_list

In [ ]:
#set_index(),重新设置索引
score_list.set_index('语文',inplace=True)   #将语文列设置为索引列
score_list
score_list.info()

# Pandas的数据类型dtype

In [ ]:
#pandas的数据类型和python基本一样，只有几个不同，例如：object对应于python的str类型，np.nan/pd.NA对应于python的None类型，datetime64对应于python的datetime类型，timedelta[ns]对应于python的timedelta类型
#此外，pandas还支持一些特殊的数据类型，例如：category类型，用于表示分类数据，sparse类型，用于表示稀疏数据，interval类型，用于表示区间数据，period类型，用于表示时间段数据，等等

In [ ]:
#创建dataframe对象，演示缺省数据类型
df=pd.DataFrame(
    {'姓名':{'学生1':'zbw','学生2':'myy','学生3':'xjx'},
     '年龄':{'学生1':18,'学生2':18,'学生3':18},
     '性别':{'学生1':'男','学生2':'男','学生3':'女'}
    }
)   #字典套字典形式
df

In [ ]:
df2=pd.DataFrame(
    {
        '姓名':['zbw',pd.NA,'xjx'],
        '年龄':[18,np.nan,18],
        '性别':['男','女',None]
    }
)
df2

In [ ]:
#演示日期时间数据类型，日期时间的常用定义格式为：xxxx-xx-xx xx:xx:xx
df3=pd.DataFrame(['2024-2-18 00:30:30','2026-12-6'], dtype='datetime64[ns]') #日期时间类型必须严格遵守现实的日期时间格式，否则会报错
df3

In [ ]:
#演示时间差timedelta类型，时间差的常用定义格式为：xx days xx:xx:xx
df4=pd.to_datetime(['2025-2-18 00:30:56'])
df4 #默认只显示最后一个表达式，后面还有语句运行就不显示
print(df4.dtype)

df5=pd.to_datetime(['2026-10-10 15:38:36'])
df5
df6=df5-df4
print(df6)
print(df6.dtype)

# Pandas基本操作

## 加载数据

In [ ]:
#加载股票数据
stock_info=pd.read_csv('./stock_day.csv')
stock_info

In [ ]:
#移除不需要的列
df_st=stock_info.drop(columns=['ma5','ma10','ma20','v_ma5','v_ma10','v_ma20','turnover'],inplace=False)
df_st
df_st.info()    #详细信息
df_st.describe() #统计信息

## 索引操作

In [ ]:
#根据行列索引获取数据
df=df_st['open']
df.info()   #结果是series对象，因为dataframe的每一行/列都是series对象
print(df_st['open']['2018-02-13'])  #必须先列后行
# df_st['2018-02-13']['open']  #错误

In [ ]:
#通过loc和iloc获取数据，可进行切片,先行后列
#loc是通过标签名字获取数据
df_st.loc['2018-02-13','open']   #获取指定行数据
df_st.loc['2018-02-13':'2018-02-27':-1,'open':'volume':2]   #通过切片获取数据，步长为-1表示倒序，执行切片时，看的是标签在原表中的位置，步长为2表示每隔一行/列取一个数据，loc的切片是包含尾数的，iloc的切片是不包含尾数的

In [ ]:
#iloc是通过位置索引获取数据
df_st.iloc[0,0]   #获取指定位置数据 第0行第0列
df_st.iloc[0:5,0:3]   #通过切片获取数据，前5行，前3列，iloc的切片是不包含尾数的，同样可以倒序

## 赋值操作

In [100]:
#查看源数据
# df_st1=df_st    #只是指向同一个对象，修改df_st1会影响df_st
df_st1=df_st.copy()  #创建副本，避免影响原数据
df_st1
#赋值
df_st1['open']=23
df_st1
df_st1.low=1    #用.的方式和中括号效果一致，但如果列名中有空格或特殊字符，就不能用.的方式赋值
df_st

             open   high  close    low     volume  price_change  p_change
2018-02-27  23.53  25.88  24.16  23.53   95578.03          0.63      2.68
2018-02-26  22.80  23.78  23.53  22.80   60985.11          0.69      3.02
2018-02-23  22.88  23.37  22.82  22.71   52914.01          0.54      2.42
2018-02-22  22.25  22.76  22.28  22.02   36105.01          0.36      1.64
2018-02-14  21.49  21.99  21.92  21.48   23331.04          0.44      2.05
...           ...    ...    ...    ...        ...           ...       ...
2015-03-06  13.17  14.48  14.28  13.13  179831.72          1.12      8.51
2015-03-05  12.88  13.45  13.16  12.87   93180.39          0.26      2.02
2015-03-04  12.80  12.92  12.90  12.61   67075.44          0.20      1.57
2015-03-03  12.52  13.06  12.70  12.52  139071.61          0.18      1.44
2015-03-02  12.25  12.67  12.52  12.20   96291.73          0.32      2.62

[643 rows x 7 columns]

In [104]:
#按照值排序
df_st.sort_values('open',ascending=False)   #按照open列的值进行排序，ascending=False表示降序，默认是升序
df_st.sort_values(['open','high'],ascending=[False,True])   #先按照open列降序排序，如果open列相同，再按照high列升序排序

             open   high  close    low     volume  price_change  p_change
2015-06-15  34.99  34.99  31.69  31.69  199369.53         -3.52    -10.00
2015-06-12  34.69  35.98  35.21  34.01  159825.88          0.82      2.38
2015-06-10  34.10  36.35  33.85  32.23  269033.12          0.51      1.53
2017-11-01  33.85  34.34  33.83  33.10  232325.30         -0.61     -1.77
2015-06-11  33.17  34.98  34.39  32.51  173075.73          0.54      1.59
...           ...    ...    ...    ...        ...           ...       ...
2015-03-05  12.88  13.45  13.16  12.87   93180.39          0.26      2.02
2015-03-04  12.80  12.92  12.90  12.61   67075.44          0.20      1.57
2015-03-03  12.52  13.06  12.70  12.52  139071.61          0.18      1.44
2015-09-02  12.30  14.11  12.36  12.30   70201.74         -1.10     -8.17
2015-03-02  12.25  12.67  12.52  12.20   96291.73          0.32      2.62

[643 rows x 7 columns]

In [105]:
#按照索引排序
df_st.sort_index(ascending=False)   #按照索引排序，ascending=False表示降
#series也可以按照索引排序

             open   high  close    low     volume  price_change  p_change
2018-02-27  23.53  25.88  24.16  23.53   95578.03          0.63      2.68
2018-02-26  22.80  23.78  23.53  22.80   60985.11          0.69      3.02
2018-02-23  22.88  23.37  22.82  22.71   52914.01          0.54      2.42
2018-02-22  22.25  22.76  22.28  22.02   36105.01          0.36      1.64
2018-02-14  21.49  21.99  21.92  21.48   23331.04          0.44      2.05
...           ...    ...    ...    ...        ...           ...       ...
2015-03-06  13.17  14.48  14.28  13.13  179831.72          1.12      8.51
2015-03-05  12.88  13.45  13.16  12.87   93180.39          0.26      2.02
2015-03-04  12.80  12.92  12.90  12.61   67075.44          0.20      1.57
2015-03-03  12.52  13.06  12.70  12.52  139071.61          0.18      1.44
2015-03-02  12.25  12.67  12.52  12.20   96291.73          0.32      2.62

[643 rows x 7 columns]

## 四则运算

In [ ]:
#加减乘除
df_st['open']+1
df_st['open'].add(2)

In [109]:
#逻辑运算
#筛选出open大于25的值
df_st[df_st['open']>25]

             open   high  close    low     volume  price_change  p_change
2018-01-24  25.49  26.28  25.29  25.20  134838.00         -0.20     -0.79
2018-01-23  25.15  25.53  25.50  24.93  104205.76          0.39      1.55
2018-01-22  25.14  25.40  25.13  24.75   68292.08         -0.01     -0.04
2017-11-23  25.30  25.43  24.03  23.98   76386.50         -1.24     -4.91
2017-11-22  25.21  25.90  25.26  24.84   68269.50         -0.03     -0.12
...           ...    ...    ...    ...        ...           ...       ...
2015-05-27  29.66  29.66  28.07  27.95  184613.42         -1.59     -5.36
2015-05-26  29.92  30.30  29.66  28.70  198210.12         -0.26     -0.87
2015-05-25  29.30  30.30  29.92  28.10  151819.52          0.38      1.29
2015-05-22  29.87  30.99  29.54  28.53  209382.62          1.32      4.68
2015-05-21  27.50  28.22  28.22  26.50  121190.11          2.57     10.02

[84 rows x 7 columns]

In [112]:
#筛选出close大于23小于25的值
#方法1：采用逻辑运算符&，需要加括号
df_st[(df_st['close']>23) & (df_st['close']<25)]
#方法2：采用query方法
df_st.query('close>23 and close<25')   #query方法中，query方法中可以直接使用列名，而不需要加引号

             open   high  close    low     volume  price_change  p_change
2018-02-27  23.53  25.88  24.16  23.53   95578.03          0.63      2.68
2018-02-26  22.80  23.78  23.53  22.80   60985.11          0.69      3.02
2018-02-05  22.45  23.39  23.27  22.25   52341.39          0.65      2.87
2018-01-31  23.85  23.98  23.72  23.31   49155.02         -0.11     -0.46
2018-01-30  23.71  24.08  23.83  23.70   32420.43          0.05      0.21
...           ...    ...    ...    ...        ...           ...       ...
2015-06-29  26.50  26.98  23.83  22.82  168452.12         -1.45     -5.74
2015-05-19  23.68  23.69  23.32  22.47   82945.73          0.25      1.08
2015-05-18  22.28  24.45  23.07  22.08  109886.22          0.79      3.55
2015-04-15  23.45  25.56  24.38  23.40  250311.59          1.14      4.91
2015-04-14  21.45  23.24  23.24  21.45  154693.44          2.11      9.99

[98 rows x 7 columns]

In [115]:
#固定值筛选，选出high等于23.78或24.74的值
df_st[(df_st['high']==23.78) | (df_st['high']==24.74)]
df_st.query('high==23.78 or high==24.74')
df_st.query('high in [23.78,24.74]')   #in方法，判断是否在列表中

             open   high  close    low    volume  price_change  p_change
2018-02-26  22.80  23.78  23.53  22.80  60985.11          0.69      3.02
2018-01-26  24.27  24.74  24.49  24.22  50601.83          0.11      0.45