# Pandas进阶

## 文件读取与存储

In [ ]:
#导包
import numpy as np
import pandas as pd

In [ ]:
#读取csv文件
#格式pd.read_csv(文件路径,参数)
#参数：
#sep：分隔符，默认是逗号
#header：指定行数作为列名，默认是0，表示第一行作为列名
#index_col：指定列作为索引，默认是None，表示不使用任何列作为索引
#usecols：指定读取的列，默认是None，表示读取所有列
#skiprows：指定跳过的行数，默认是None，表示不跳过任何行
#nrows：指定读取的行数，默认是None，表示读取所有行
#encoding：指定编码格式，默认是None，表示使用系统默认编码
df=pd.read_csv('./stock_day.csv',sep=',',usecols=['open','high','close','low'],index_col=0,encoding='utf-8')    #这里由于实际数据列数比列名多一列，即使不写index_col=0也会自动把第一列作为索引，规范的写法是指定第0列作为索引
df

In [ ]:
#写入csv文件
#格式df.to_csv(文件路径,参数)
#参数：
#sep：分隔符，默认是逗号
#index：是否写入索引，默认是True，表示写入索引
#header：是否写入列名，默认是True，表示写入列名
#encoding：指定编码格式，默认是None，表示使用系统默认编码

#取df的后10行数据，写入csv文件
df.tail(10).to_csv('./my_files1.csv',sep=',',index=True,encoding='utf-8')
print('写入成功')   #由于指定了索引，所以写入的csv文件第一列是索引列，但是索引列没有列名，文件开头就会有一个，号

In [ ]:
#有个特殊的文件格式是tsv文件，tsv文件是以制表符\t分隔的文本文件，类似于csv文件，但是分隔符是制表符，而不是逗号，读取tsv文件时还是用read_csv()函数，只是指定sep='\t'，写入tsv文件时用to_csv()函数，指定sep='\t'即可
#写入tsv文件
df.head(10).to_csv('./my_files2.tsv',sep='\t',index=True,encoding='utf-8')

In [ ]:
#查看当前python环境
import sys
sys.executable

In [ ]:
#读取json文件
#格式pd.read_json(文件路径,参数)
#参数：
#orient：指定json文件的格式，默认是None，表示自动推断格式，可选值有：
#'split'：分割格式，表示json文件是由索引、列名和数据组成的字典，类似于Dataframe的to_dict()方法
#'records'：记录格式，表示json文件是由一系列字典组成的列表，类似于Dataframe的to_dict(orient='records')方法
#'index'：索引格式，表示json文件是由索引和数据组成的字典，类似于Dataframe的to_dict(orient='index')方法
#'columns'：列格式，表示json文件是由列名和数据组成的字典，类似于Dataframe的to_dict(orient='columns')方法
#'values'：值格式，表示json文件是由数据组成的列表，类似于Dataframe的to_dict(orient='values')方法
#lines：指定是否按行读取json文件，默认是False，表示按整个文件读取，可选值有True，表示按行读取
df_json=pd.read_json('./test.json',encoding='utf-8',orient='records',lines=True)
df_json

In [ ]:
#写入json文件
#格式df.to_json(文件路径,参数)
#参数：
#orient：指定json文件的格式，默认是None，表示自动推断格式
#lines：指定是否按行写入json文件，默认是False，表示按整个文件写入，可选值有True，表示按行写入
#无encoding参数，写入json文件时默认使用utf-8编码
df_json.to_json('./my_files3.json',orient='records',lines=True)
print('写入成功')

## 通过python操作MYSQL数据库

In [ ]:
#读取数据
data=pd.read_csv('./csv示例文件.csv',sep=',',encoding='gbk')
data

In [ ]:
#把数据写入mysql数据库
#首先要导包：pymysql和sqlalchemy
import pymysql
from sqlalchemy import create_engine

In [ ]:
#创建数据库连接引擎
#格式：create_engine('数据库+模块名://用户名:密码@主机地址:端口号/数据库名?charset=编码方式')
engine=create_engine('mysql+pymysql://root:123456@localhost:3306/day01?charset=utf8')

In [ ]:
#把数据写入mysql数据库
#格式：df.to_sql(表名,数据库连接引擎,参数)
#参数：
#if_exists：指定表存在时的处理方式，默认是fail，表示如果表存在就报错，其他可选值有replace，表示如果表存在就删除表重新创建表，append，表示如果表存在就追加数据
#index：是否写入索引，默认是True，表示把Dataframe索引写入数据库
data.to_sql('my_table',engine,if_exists='append',index=False)
print('写入成功')

In [15]:
#从sql表中读取数据
#格式：pd.read_sql(表名,数据库连接引擎,参数)
#参数：
#index_col：指定列作为索引，默认是None，表示不使用任何列作为索引
data_sql=pd.read_sql('product',engine)
print('读取成功')
data_sql

## 增删改查操作

In [16]:
#准备数据
data=pd.read_csv('./1960-2019全球GDP数据.csv',sep=',',encoding='gbk')
data

      year   country           GDP
0     1960        美国  543300000000
1     1960        英国   73233967692
2     1960        法国   62225478000
3     1960        中国   59716467625
4     1960        日本   44307342950
...    ...       ...           ...
9925  2019  圣多美和普林西比     418637388
9926  2019        帕劳     268354919
9927  2019      基里巴斯     194647201
9928  2019        瑙鲁     118223430
9929  2019       图瓦卢      47271463

[9930 rows x 3 columns]

In [21]:
#截取部分数据
data1=data.iloc[:5,:].copy()
data1

   year country           GDP
0  1960      美国  543300000000
1  1960      英国   73233967692
2  1960      法国   62225478000
3  1960      中国   59716467625
4  1960      日本   44307342950

In [18]:
#增：增加一行/列数据
#方法1：使用列名+赋值/loc方式直接增加一列/行数据
data1['new_cli2']=23 #整体赋值
data1['new_cli1']=[1,2,3,4,5] #按行赋值
# data1.loc[5]=[6,'7',8,9,10]    #按行赋值
data1['new_cli3']=data1.year*2  #用其他列计算新列

In [19]:
#方法2：使用assign()方法增加一列数据,该方法不会修改原数据，而是返回一个新的DataFrame对象
data1=data1.assign(new_cli4=data1.year*3)
data1=data1.assign(
    c1=1,
    c2=data1.year*4,
    c3=[1,1,1,1,1]
)
data1

,year,country,GDP,new_cli2,new_cli1,new_cli3,new_cli4,c1,c2,c3
0,1960,美国,543300000000,23,1,3920,5880,1,7840,1
1,1960,英国,73233967692,23,2,3920,5880,1,7840,1
2,1960,法国,62225478000,23,3,3920,5880,1,7840,1
3,1960,中国,59716467625,23,4,3920,5880,1,7840,1
4,1960,日本,44307342950,23,5,3920,5880,1,7840,1

In [33]:
#删：删除一行/列数据
#准备数据
data2=data.iloc[:10,:].copy()
data2

   year country           GDP
0  1960      美国  543300000000
1  1960      英国   73233967692
2  1960      法国   62225478000
3  1960      中国   59716467625
4  1960      日本   44307342950
5  1960     加拿大   40461721692
6  1960     意大利   40385288344
7  1960      印度   37029883875
8  1960    澳大利亚   18577668271
9  1960      瑞典   15822585033

In [34]:

#方法1：使用drop()方法删除一行/列数据,该方法不会修改原数据，而是返回一个新的DataFrame对象
data2.drop(index=[0],inplace=True)   #删除第0行数据
data2

   year country          GDP
1  1960      英国  73233967692
2  1960      法国  62225478000
3  1960      中国  59716467625
4  1960      日本  44307342950
5  1960     加拿大  40461721692
6  1960     意大利  40385288344
7  1960      印度  37029883875
8  1960    澳大利亚  18577668271
9  1960      瑞典  15822585033

In [31]:
#方法2：使用del关键字删除一列数据,不能删除行,del关键字会直接修改原数据
data3=data2.copy()
del data3['year']
data3
#del一次只能删除一列
# del data3[['country','GDP']]      错误

  country          GDP
1      英国  73233967692
2      法国  62225478000
3      中国  59716467625
4      日本  44307342950
5     加拿大  40461721692
6     意大利  40385288344
7      印度  37029883875
8    澳大利亚  18577668271
9      瑞典  15822585033

In [35]:
#要同时删除多列，可以使用drop()方法
data2.drop(columns=['country','GDP'],inplace=True)
data2

   year
1  1960
2  1960
3  1960
4  1960
5  1960
6  1960
7  1960
8  1960
9  1960

In [39]:
#去重
#先进行拼接，保证有重复数据
data3=data.iloc[:6,:].copy()
data4=pd.concat([data3,data3])
data4

   year country           GDP
0  1960      美国  543300000000
1  1960      英国   73233967692
2  1960      法国   62225478000
3  1960      中国   59716467625
4  1960      日本   44307342950
5  1960     加拿大   40461721692
0  1960      美国  543300000000
1  1960      英国   73233967692
2  1960      法国   62225478000
3  1960      中国   59716467625
4  1960      日本   44307342950
5  1960     加拿大   40461721692

In [42]:
#按列去重
#duplicated()方法返回一个布尔型Series，表示每一行是否重复，第一次出现的数据保留为 False，后面重复出现的标记为 True。    keep参数表示保留哪一行，默认是'first'，表示保留第一次出现的行，其他可选值有'last'，表示保留最后一次出现的行，False，表示不保留任何重复的行
p1=data4.duplicated()
p1      #判断哪行重复

0    False
1    False
2    False
3    False
4    False
5    False
0     True
1     True
2     True
3     True
4     True
5     True
dtype: bool

In [44]:
data4.drop_duplicates(inplace=True)
data4

   year country           GDP
0  1960      美国  543300000000
1  1960      英国   73233967692
2  1960      法国   62225478000
3  1960      中国   59716467625
4  1960      日本   44307342950
5  1960     加拿大   40461721692

In [57]:
#series去重，以列做单位去重
#取出国家列
data5=data.copy()
data6=data5.country.drop_duplicates()
data6

0          美国
1          英国
2          法国
3          中国
4          日本
        ...
6462    美属萨摩亚
7492       瑙鲁
7604      南苏丹
8269      库拉索
8292    荷属圣马丁
Name: country, Length: 210, dtype: str

In [59]:
#修改数据
data7=data.iloc[:8,:].copy()
data7

   year country           GDP
0  1960      美国  543300000000
1  1960      英国   73233967692
2  1960      法国   62225478000
3  1960      中国   59716467625
4  1960      日本   44307342950
5  1960     加拿大   40461721692
6  1960     意大利   40385288344
7  1960      印度   37029883875

In [62]:
#修改GDP的值
#直接修改源数据
data7['GDP']=[1,2,3,4,5,67,6,9]
data7

   year country  GDP
0  1960      美国    1
1  1960      英国    2
2  1960      法国    3
3  1960      中国    4
4  1960      日本    5
5  1960     加拿大   67
6  1960     意大利    6
7  1960      印度    9

In [67]:
#replace()方法
data8=data7.country.replace('日本','小日本')
data8
# data7.country.replace('美国','老美', inplace=True)
#新版pandas会把data7.country看成一个临时series，修改的数据不再是data7那一列数据本身，因此使用inplace关键字会报错

0     美国
1     英国
2     法国
3     中国
4    小日本
5    加拿大
6    意大利
7     印度
Name: country, dtype: str

In [71]:
#查数据
data9=data.copy()
data9

      year   country           GDP
0     1960        美国  543300000000
1     1960        英国   73233967692
2     1960        法国   62225478000
3     1960        中国   59716467625
4     1960        日本   44307342950
...    ...       ...           ...
9925  2019  圣多美和普林西比     418637388
9926  2019        帕劳     268354919
9927  2019      基里巴斯     194647201
9928  2019        瑙鲁     118223430
9929  2019       图瓦卢      47271463

[9930 rows x 3 columns]

In [76]:
#直接用索引查询
data9.loc[3:10,['country','GDP']]
data9.iloc[0:10:2,[1,2]]

  country           GDP
0      美国  543300000000
2      法国   62225478000
4      日本   44307342950
6     意大利   40385288344
8    澳大利亚   18577668271

In [77]:
#使用query函数查找
data9.query('country in ["中国","俄罗斯","日本","美国"] and year in [2015,2016,2017,2018]')

      year country             GDP
8928  2015      美国  18224700000000
8929  2015      中国  11061600000000
8930  2015      日本   4389480000000
8939  2015     俄罗斯   1363480000000
9133  2016      美国  18715000000000
9134  2016      中国  11233300000000
9135  2016      日本   4922540000000
9144  2016     俄罗斯   1276790000000
9338  2017      美国  19519400000000
9339  2017      中国  12310400000000
9340  2017      日本   4866860000000
9349  2017     俄罗斯   1574200000000
9542  2018      美国  20580200000000
9543  2018      中国  13894800000000
9544  2018      日本   4954810000000
9553  2018     俄罗斯   1669580000000

## 排序

In [78]:
#sort_index函数，根据索引排序
data9.sort_index(ascending=False)

      year   country           GDP
9929  2019       图瓦卢      47271463
9928  2019        瑙鲁     118223430
9927  2019      基里巴斯     194647201
9926  2019        帕劳     268354919
9925  2019  圣多美和普林西比     418637388
...    ...       ...           ...
4     1960        日本   44307342950
3     1960        中国   59716467625
2     1960        法国   62225478000
1     1960        英国   73233967692
0     1960        美国  543300000000

[9930 rows x 3 columns]

In [79]:
#sort_values根据列的值进行排序
#更具year降序，year一样，更具GDP升序
data9.sort_values(['year','GDP'],ascending=[False,True])

      year   country           GDP
9929  2019       图瓦卢      47271463
9928  2019        瑙鲁     118223430
9927  2019      基里巴斯     194647201
9926  2019        帕劳     268354919
9925  2019  圣多美和普林西比     418637388
...    ...       ...           ...
4     1960        日本   44307342950
3     1960        中国   59716467625
2     1960        法国   62225478000
1     1960        英国   73233967692
0     1960        美国  543300000000

[9930 rows x 3 columns]

In [82]:
#rank()函数，分为密集排序和稀疏排序
#准备数据
df_score=pd.DataFrame({'姓名':['zbw','xjx','myy','xxd'],
                       '成绩':[100,90,90,80]
                       })
df_score.index=(1,2,3,4)
df_score

    姓名   成绩
1  zbw  100
2  xjx   90
3  myy   90
4  xxd   80

In [83]:
#排序,默认情况下，会返回一个排名列表
df_score.rank()

    姓名   成绩
1  4.0  4.0
2  2.0  2.5
3  1.0  2.5
4  3.0  1.0

In [87]:
#进阶用法；新增一列用来记录排名，相当于窗口函数
df_score['排名_max']=df_score['成绩'].rank(method='max',ascending=False)
df_score['排名_min']=df_score['成绩'].rank(method='min',ascending=False)
df_score['排名_avg']=df_score['成绩'].rank(method='average',ascending=False)
df_score['排名_dense']=df_score['成绩'].rank(method='dense',ascending=False)
df_score['排名_默认']=df_score['成绩'].rank(ascending=False)      #默认是平均排序
df_score

    姓名   成绩  排名_max  排名_min  排名_avg  排名_dense  排名_默认
1  zbw  100     1.0     1.0     1.0       1.0    1.0
2  xjx   90     3.0     2.0     2.5       2.0    2.5
3  myy   90     3.0     2.0     2.5       2.0    2.5
4  xxd   80     4.0     4.0     4.0       3.0    4.0