# RFM案例分析

RFM模型是一种常见的客户分析模型，主要用于电商、零售、会员运营、用户分层。
R、F、M分别代表Recency最近一次消费时间，Frequency消费频率，Moneatry消费金额
R=今天减去最近一次消费日期，数值越小说明客户越活跃
通过三者的评分进行占比评估，原来确立用户画像，通常情况下金额占比最大

RFM模型的基本实现过程
1、设置要计算时的截止时间节点

In [ ]:
#导包
import numpy as np
import pandas as pd
import os
import time
import pymysql
from pyecharts.charts.three_axis_charts import bar3D
from sqlalchemy import create_engine
#数据可视化工具，可绘制交互式图表
import pyecharts.options as opts
from pyecharts.charts import Bar3D
from pyecharts.commons.utils import JsCode

os.getcwd()

## 准备数据

In [ ]:
#定义列表，记录读取文件的列表名字
sheet_names=['2015','2016','2017','2018','会员等级']
sheet_dict=pd.read_excel('./sales.xlsx',sheet_name=sheet_names)
sheet_dict

In [ ]:
print(type(sheet_dict))     #读取多个工作表返回字典
sheet_dict['2015']          #获取其中一个表，键值对形式
# sheet_dict['2015'].info()   #查看详细信息
# sheet_dict['2015'].describe(include='all') #include=all会查看所有列的统计信息，不填只会统计数值列

In [ ]:
#遍历所有表，查看数据
for i in sheet_names:
    print(i)
    print(sheet_dict[i].info())
    print(sheet_dict[i].describe())

## 数据预处理

In [ ]:
#遍历
for i in sheet_names[:-1]:  #除了最后一张表不要
    #删除缺失值
    sheet_dict[i]=sheet_dict[i].dropna(axis=0)
    #筛选出订单金额大于1的订单
    sheet_dict[i]=sheet_dict[i][sheet_dict[i]['订单金额']>1]
    #固定时间节点，以每年最后一天为该年份评估的截止时间
    sheet_dict[i]['max_end_data']=pd.to_datetime(sheet_dict[i]['提交日期'].dt.year.astype(str)+'-12-31')
    # sheet_dict[i]['max_end_data']=sheet_dict[i]['提交日期']+pd.offsets.YearEnd(0)

In [ ]:
#合并上述表格称为一个表，使用pd.concat实现垂直合并（merge无法实现），传入concat的必须是df和series数据类型
# merge=pd.DataFrame()
# for i in sheet_names[:-1]:
#     merge=pd.concat([merge,sheet_dict[i]],ignore_index=True)
#列表推导式
merge=pd.concat([sheet_dict[i] for i in sheet_names[:-1]],ignore_index=True)
merge

In [ ]:
#新增year列，方便后续分组
merge['year']=merge['提交日期'].dt.year
type(merge.year[1])

In [ ]:
#新增本订单时间距离评估年份截止时间的差值
merge['diff_date']=merge['max_end_data']-merge['提交日期']
merge

In [ ]:
#将差值转换为int类型
merge['diff_date']=merge['diff_date'].dt.days
merge

## 数据的统计分析

In [28]:
#基于会员ID和年份，计算R，F，M
merge_RFM=merge.groupby(['会员ID','year'],as_index=False).agg({'diff_date':'min',
                                                '订单号':'count',
                                                '订单金额':'sum'
                                                })
merge_RFM.columns=['会员id','year','R','F','M']
merge_RFM.index
merge_RFM

               会员id  year    R  F       M
0                81  2016    2  2   159.1
1               267  2015  197  2   105.0
2               278  2016    2  2   548.5
3               278  2017   67  3  7137.0
4               278  2018   36  1    49.9
...             ...   ...  ... ..     ...
148586  39545536113  2016  254  1  2399.0
148587  39545538296  2017  279  1   375.0
148588  39546132904  2015  316  1   149.7
148589  39546134364  2015  242  1    49.0
148590  39546136285  2018  163  1    19.9

[148591 rows x 5 columns]

In [ ]:
#查看RFM分布情况
merge_RFM.iloc[:,2:].describe().T

In [ ]:
#划分区间，给出DFM的评分，R：最近一次购买时间，越小越好；F：越大越好；M：越大越好
#思路1：给出指定区间树，系统自动划分
pd.cut(merge_RFM['F'],bins=3)   #pd.cut划分的区间为左开右闭
pd.cut(merge_RFM['R'],bins=3)

In [ ]:
#给出指定边界，系统自动划分区间数
R_bins=[-1,79,156,255,365]   #注意区间划分时为左开右闭
F_bins=[0,2,5,10,130]
M_bins=[1,69,189,1199,206252]

In [29]:
#划分区间，并给出评分
merge_RFM['R_score']=pd.cut(merge_RFM['R'],bins=R_bins,labels=[i for i in range(len(R_bins)-1,0,-1)])
merge_RFM['F_score']=pd.cut(merge_RFM['F'],bins=F_bins,labels=[i for i in range(1,len(F_bins),1)])
merge_RFM['M_score']=pd.cut(merge_RFM['M'],bins=M_bins,labels=[i for i in range(1,len(M_bins),1)])
merge_RFM

               会员id  year    R  F       M R_score F_score M_score
0                81  2016    2  2   159.1       4       1       2
1               267  2015  197  2   105.0       2       1       2
2               278  2016    2  2   548.5       4       1       3
3               278  2017   67  3  7137.0       4       2       4
4               278  2018   36  1    49.9       4       1       1
...             ...   ...  ... ..     ...     ...     ...     ...
148586  39545536113  2016  254  1  2399.0       2       1       4
148587  39545538296  2017  279  1   375.0       1       1       3
148588  39546132904  2015  316  1   149.7       1       1       2
148589  39546134364  2015  242  1    49.0       2       1       1
148590  39546136285  2018  163  1    19.9       2       1       1

[148591 rows x 8 columns]

In [30]:
#统计所有会员的年度评分，拼接
merge_RFM['ALL']=merge_RFM['R_score'].astype(str)+merge_RFM['F_score'].astype(str)+merge_RFM['M_score'].astype(str)
merge_RFM

               会员id  year    R  F       M R_score F_score M_score  ALL
0                81  2016    2  2   159.1       4       1       2  412
1               267  2015  197  2   105.0       2       1       2  212
2               278  2016    2  2   548.5       4       1       3  413
3               278  2017   67  3  7137.0       4       2       4  424
4               278  2018   36  1    49.9       4       1       1  411
...             ...   ...  ... ..     ...     ...     ...     ...  ...
148586  39545536113  2016  254  1  2399.0       2       1       4  214
148587  39545538296  2017  279  1   375.0       1       1       3  113
148588  39546132904  2015  316  1   149.7       1       1       2  112
148589  39546134364  2015  242  1    49.0       2       1       1  211
148590  39546136285  2018  163  1    19.9       2       1       1  211

[148591 rows x 9 columns]

## 导出结果

- 导出到excel

In [33]:
#保存结果为excel
merge_RFM.to_excel('./RFM_group.xlsx',index=False)  #忽略索引列

- 导出到mysql

In [20]:
#创建引擎
engine=create_engine('mysql+pymysql://root:123456@localhost:3306/RFM?charset=utf8')

In [34]:
#导出到数据库 参1：表名字；参2：引擎；参3：忽略索引；参4：存在则替换
merge_RFM.to_sql('rfm_table',engine,index=False,if_exists='replace')
print('导入成功')

导入成功

In [35]:
#读取数据
pd.read_sql('select * from rfm_table',engine)

               会员id  year    R  F       M R_score F_score M_score  ALL
0                81  2016    2  2   159.1       4       1       2  412
1               267  2015  197  2   105.0       2       1       2  212
2               278  2016    2  2   548.5       4       1       3  413
3               278  2017   67  3  7137.0       4       2       4  424
4               278  2018   36  1    49.9       4       1       1  411
...             ...   ...  ... ..     ...     ...     ...     ...  ...
148586  39545536113  2016  254  1  2399.0       2       1       4  214
148587  39545538296  2017  279  1   375.0       1       1       3  113
148588  39546132904  2015  316  1   149.7       1       1       2  112
148589  39546134364  2015  242  1    49.0       2       1       1  211
148590  39546136285  2018  163  1    19.9       2       1       1  211

[148591 rows x 9 columns]

## 数据可视化

In [43]:
#将结果根据'年份+评级'分组
display_RFM=merge_RFM.groupby(['year','ALL'],as_index=False).agg({'会员id':'count',})
display_RFM.columns=['年份','会员评级','人数']
display_RFM['人数'].info()
display_RFM

<class 'pandas.Series'>
RangeIndex: 162 entries, 0 to 161
Series name: 人数
Non-Null Count  Dtype
--------------  -----
162 non-null    int64
dtypes: int64(1)
memory usage: 1.4 KB

       年份 会员评级    人数
0    2015  111  2180
1    2015  112  1979
2    2015  113  1832
3    2015  114  1785
4    2015  122     4
..    ...  ...   ...
157  2018  432     1
158  2018  433    22
159  2018  434   244
160  2018  442     1
161  2018  444   111

[162 rows x 3 columns]

In [71]:
#将数据转成列表
data=display_RFM[['年份','会员评级','人数']].values     #用values取值时会返回一个ndarray类型
data=data.tolist()
type(data)
data

[[2015, '111', 2180],
 [2015, '112', 1979],
 [2015, '113', 1832],
 [2015, '114', 1785],
 [2015, '122', 4],
 [2015, '123', 23],
 [2015, '124', 24],
 [2015, '134', 5],
 [2015, '144', 10],
 [2015, '211', 2093],
 [2015, '212', 2032],
 [2015, '213', 1838],
 [2015, '214', 1737],
 [2015, '221', 1],
 [2015, '222', 2],
 [2015, '223', 16],
 [2015, '224', 12],
 [2015, '234', 1],
 [2015, '244', 1],
 [2015, '311', 1439],
 [2015, '312', 1338],
 [2015, '313', 1368],
 [2015, '314', 1225],
 [2015, '321', 1],
 [2015, '322', 5],
 [2015, '323', 20],
 [2015, '324', 25],
 [2015, '334', 1],
 [2015, '344', 17],
 [2015, '411', 1718],
 [2015, '412', 1651],
 [2015, '413', 1659],
 [2015, '414', 1440],
 [2015, '421', 6],
 [2015, '422', 13],
 [2015, '423', 48],
 [2015, '424', 44],
 [2015, '433', 3],
 [2015, '434', 7],
 [2015, '444', 8],
 [2016, '111', 1498],
 [2016, '112', 1540],
 [2016, '113', 1418],
 [2016, '114', 1297],
 [2016, '144', 233],
 [2016, '211', 2629],
 [2016, '212', 2528],
 [2016, '213', 2508],
 [2016, '214', 2272],
 [2016, '221', 2],
 [2016, '222', 3],
 [2016, '223', 12],
 [2016, '224', 10],
 [2016, '244', 9],
 [2016, '311', 2049],
 [2016, '312', 2058],
 [2016, '313', 1889],
 [2016, '314', 1764],
 [2016, '321', 4],
 [2016, '322', 8],
 [2016, '323', 46],
 [2016, '324', 32],
 [2016, '333', 4],
 [2016, '334', 17],
 [2016, '344', 24],
 [2016, '411', 2171],
 [2016, '412', 2210],
 [2016, '413', 2228],
 [2016, '414', 1947],
 [2016, '421', 9],
 [2016, '422', 12],
 [2016, '423', 74],
 [2016, '424', 64],
 [2016, '432', 1],
 [2016, '433', 7],
 [2016, '434', 10],
 [2016, '444', 18],
 [2017, '111', 3169],
 [2017, '112', 2971],
 [2017, '113', 2766],
 [2017, '114', 2506],
 [2017, '121', 1],
 [2017, '122', 3],
 [2017, '123', 9],
 [2017, '124', 4],
 [2017, '144', 36],
 [2017, '211', 1539],
 [2017, '212', 1501],
 [2017, '213', 1530],
 [2017, '214', 1385],
 [2017, '222', 6],
 [2017, '223', 10],
 [2017, '224', 11],
 [2017, '234', 1],
 [2017, '244', 3],
 [2017, '311', 1970],
 [2017, '312', 1992],
 [2017, '313', 1960],
 [2017, '314', 1598],
 [2017, '321', 3],
 [2017, '322', 6],
 [2017, '323', 24],
 [2017, '324', 27],
 [2017, '334', 1],
 [2017, '344', 584],
 [2017, '411', 2164],
 [2017, '412', 2183],
 [2017, '413', 2142],
 [2017, '414', 1946],
 [2017, '421', 2],
 [2017, '422', 9],
 [2017, '423', 55],
 [2017, '424', 60],
 [2017, '431', 1],
 [2017, '433', 2],
 [2017, '434', 9],
 [2017, '444', 78],
 [2018, '111', 2271],
 [2018, '112', 2301],
 [2018, '113', 2039],
 [2018, '114', 1947],
 [2018, '121', 8],
 [2018, '122', 86],
 [2018, '123', 890],
 [2018, '124', 1904],
 [2018, '133', 2],
 [2018, '134', 76],
 [2018, '144', 112],
 [2018, '211', 3448],
 [2018, '212', 3447],
 [2018, '213', 3238],
 [2018, '214', 2925],
 [2018, '221', 4],
 [2018, '222', 5],
 [2018, '223', 44],
 [2018, '224', 81],
 [2018, '234', 5],
 [2018, '244', 307],
 [2018, '311', 3856],
 [2018, '312', 3876],
 [2018, '313', 3736],
 [2018, '314', 3464],
 [2018, '321', 9],
 [2018, '322', 32],
 [2018, '323', 135],
 [2018, '324', 172],
 [2018, '333', 9],
 [2018, '334', 32],
 [2018, '344', 43],
 [2018, '411', 3221],
 [2018, '412', 3254],
 [2018, '413', 3328],
 [2018, '414', 3008],
 [2018, '421', 17],
 [2018, '422', 29],
 [2018, '423', 170],
 [2018, '424', 198],
 [2018, '432', 1],
 [2018, '433', 22],
 [2018, '434', 244],
 [2018, '442', 1],
 [2018, '444', 111]]

In [64]:
#定义颜色映射列表
range_color = [
    '#313695', '#4575b4', '#74add1',
    '#abd9e9', '#e0f3f8', '#ffffbf',
    '#fee090', '#fdae61', '#f46d43',
    '#d73027', '#a50026']   #颜色的映射次序取决于定义颜色列表的顺序
#找到映射最大值
range_max=max(row[2] for row in data)
range_max

3876

In [72]:
 #创建三维柱状图
C=(
    Bar3D()
    .add(
        "",
        data,
        xaxis3d_opts=opts.Axis3DOpts(type_="category",name='年份'),
        yaxis3d_opts=opts.Axis3DOpts(type_='category',name='会员评级'),
        zaxis3d_opts=opts.Axis3DOpts(type_='value',name='人数')
    )
    .set_global_opts(
        visualmap_opts=opts.VisualMapOpts(max_=range_max,range_color=range_color),
        title_opts=opts.TitleOpts(title='RFM分组结果')  #标题
    )
)
# C.render('RFM分组结果.html')
# C.render_notebook()
from pathlib import Path

path = Path(C.render('RFM分组结果_修复.html'))
html = path.read_text(encoding='utf-8')

html = html.replace(
    'https://assets.pyecharts.org/assets/v6/echarts.min.js',
    'https://cdn.jsdelivr.net/npm/echarts@5.6.0/dist/echarts.min.js'
).replace(
    'https://assets.pyecharts.org/assets/v6/echarts-gl.min.js',
    'https://cdn.jsdelivr.net/npm/echarts-gl@2.0.9/dist/echarts-gl.min.js'
)

path.write_text(html, encoding='utf-8')

24081